export type FieldType = 'text' | 'textarea' | 'select' | 'multiselect';

export interface FieldDef {
  key: string;
  label: string;
  type: FieldType;
  options?: string[];
  refCategory?: string;
  tooltip?: string;
}

export interface CategoryDef {
  key: string;
  label: string;
  prefix: string;
  icon: string;
  fields: FieldDef[];
}

const STATUS_OPTIONS = ['Aktiv', 'Inaktiv', 'In Planung', 'Außer Betrieb'];

export const CATEGORIES: CategoryDef[] = [
  {
    key: 'geschaeftsprozesse',
    label: 'Geschäftsprozesse',
    prefix: 'GP',
    icon: '⚙️',
    fields: [
      { key: 'kuerzel', label: 'Kürzel', type: 'text', tooltip: 'Standardisierte Nomenklatur zur Zuordnung (z.B. GP-001)' },
      { key: 'name', label: 'Name', type: 'text', tooltip: 'Name des Geschäftsprozesses mit Wiedererkennungswert' },
      { key: 'erlaeuterung', label: 'Erläuterung', type: 'textarea', tooltip: 'Beschreibung des Geschäftsprozesses und seiner Einbettung' },
      { key: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS, tooltip: 'Aktueller Lebenszyklus des Objekts' },
      { key: 'prozessArt', label: 'Prozess-Art', type: 'select', options: ['Kernprozess', 'Unterstützungsprozess'], tooltip: 'Kernprozesse tragen zur Erreichung der Geschäftsziele bei; Unterstützungsprozesse unterstützen diese indirekt' },
      { key: 'verantwortlicher', label: 'Verantwortlicher / Fachabteilung', type: 'text', tooltip: 'Verantwortliche Person oder Abteilung' },
      { key: 'beteiligte', label: 'Beteiligte', type: 'text', tooltip: 'Beteiligte Personen oder Abteilungen' },
      { key: 'tags', label: 'Tags', type: 'text', tooltip: 'Schlüsselwörter zur Filterfunktion' },
      { key: 'daten', label: 'Daten', type: 'multiselect', refCategory: 'daten', tooltip: 'Verknüpfte Datenobjekte' },
      { key: 'anwendungen', label: 'Anwendungen', type: 'multiselect', refCategory: 'anwendungen', tooltip: 'Verknüpfte Anwendungen' },
    ],
  },
  {
    key: 'daten',
    label: 'Daten',
    prefix: 'D',
    icon: '🗄️',
    fields: [
      { key: 'kuerzel', label: 'Kürzel', type: 'text' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'erlaeuterung', label: 'Erläuterung', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS },
      { key: 'personenbezug', label: 'Personenbezug', type: 'select', options: ['Ja', 'Nein'], tooltip: 'Ob personenbezogene Daten verarbeitet werden (relevant für Datenschutz/Compliance)' },
      { key: 'verantwortlicher', label: 'Verantwortlicher / Fachabteilung', type: 'text' },
      { key: 'beteiligte', label: 'Beteiligte', type: 'text' },
      { key: 'tags', label: 'Tags', type: 'text' },
      { key: 'anwendungen', label: 'Anwendungen', type: 'multiselect', refCategory: 'anwendungen' },
    ],
  },
  {
    key: 'anwendungen',
    label: 'Anwendungen',
    prefix: 'A',
    icon: '💻',
    fields: [
      { key: 'kuerzel', label: 'Kürzel', type: 'text' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'erlaeuterung', label: 'Erläuterung', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS },
      { key: 'verantwortlicher', label: 'Verantwortlich / Administrator', type: 'text' },
      { key: 'benutzer', label: 'Benutzer', type: 'text' },
      { key: 'tags', label: 'Tags', type: 'text' },
      { key: 'anwendungen', label: 'Anwendungen', type: 'multiselect', refCategory: 'anwendungen' },
      { key: 'itSysteme', label: 'IT-Systeme', type: 'multiselect', refCategory: 'all_it', tooltip: 'Server, Clients, ICS- und IoT-Systeme' },
      { key: 'netzverbindungen', label: 'Netzverbindungen', type: 'multiselect', refCategory: 'netzverbindungen' },
    ],
  },
  {
    key: 'datentraeger',
    label: 'Datenträger',
    prefix: 'DT',
    icon: '💾',
    fields: [
      { key: 'kuerzel', label: 'Kürzel', type: 'text' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'erlaeuterung', label: 'Erläuterung', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS },
      { key: 'anzahl', label: 'Anzahl', type: 'text', tooltip: 'Stückzahl gleichartiger Datenträger in einer Gruppe' },
      { key: 'verantwortlicher', label: 'Verantwortlich / Administrator', type: 'text' },
      { key: 'benutzer', label: 'Benutzer', type: 'text' },
      { key: 'tags', label: 'Tags', type: 'text' },
      { key: 'daten', label: 'Daten', type: 'multiselect', refCategory: 'daten' },
      { key: 'anwendungen', label: 'Anwendungen', type: 'multiselect', refCategory: 'anwendungen' },
    ],
  },
  {
    key: 'server',
    label: 'Server',
    prefix: 'S',
    icon: '🖥️',
    fields: [
      { key: 'kuerzel', label: 'Kürzel', type: 'text' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'erlaeuterung', label: 'Erläuterung', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS },
      { key: 'anzahl', label: 'Anzahl', type: 'text' },
      { key: 'plattform', label: 'Plattform', type: 'text', tooltip: 'Hardware- oder Softwaregrundlage (z.B. Windows Server 2022, Linux)' },
      { key: 'verantwortlicher', label: 'Verantwortlich / Administrator', type: 'text' },
      { key: 'benutzer', label: 'Benutzer', type: 'text' },
      { key: 'tags', label: 'Tags', type: 'text' },
      { key: 'anwendungen', label: 'Anwendungen', type: 'multiselect', refCategory: 'anwendungen' },
      { key: 'itSysteme', label: 'IT-Systeme', type: 'multiselect', refCategory: 'all_it' },
      { key: 'netzverbindungen', label: 'Netzverbindungen', type: 'multiselect', refCategory: 'netzverbindungen' },
      { key: 'raeume', label: 'Räume', type: 'multiselect', refCategory: 'raeume' },
      { key: 'gebaeude', label: 'Gebäude', type: 'multiselect', refCategory: 'gebaeude' },
    ],
  },
  {
    key: 'netzkomponenten',
    label: 'Netzkomponenten',
    prefix: 'NK',
    icon: '🔌',
    fields: [
      { key: 'kuerzel', label: 'Kürzel', type: 'text' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'erlaeuterung', label: 'Erläuterung', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS },
      { key: 'anzahl', label: 'Anzahl', type: 'text' },
      { key: 'plattform', label: 'Plattform', type: 'text' },
      { key: 'verantwortlicher', label: 'Verantwortlich / Administrator', type: 'text' },
      { key: 'tags', label: 'Tags', type: 'text' },
      { key: 'itSysteme', label: 'IT-Systeme', type: 'multiselect', refCategory: 'all_it' },
      { key: 'netzverbindungen', label: 'Netzverbindungen', type: 'multiselect', refCategory: 'netzverbindungen' },
      { key: 'raeume', label: 'Räume', type: 'multiselect', refCategory: 'raeume' },
      { key: 'gebaeude', label: 'Gebäude', type: 'multiselect', refCategory: 'gebaeude' },
    ],
  },
  {
    key: 'netzverbindungen',
    label: 'Netzverbindungen',
    prefix: 'N',
    icon: '🌐',
    fields: [
      { key: 'kuerzel', label: 'Kürzel', type: 'text' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'erlaeuterung', label: 'Erläuterung', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS },
      { key: 'protokolle', label: 'Protokolle', type: 'text', tooltip: 'Genutzte Protokolle (z.B. IEEE 802.11, L2TP/IPsec, SIP)' },
      { key: 'externNetz', label: 'Externes Netz', type: 'select', options: ['Ja', 'Nein'], tooltip: 'Ob Schnittstellen nach außen (außerhalb der Institution) vorliegen' },
      { key: 'tags', label: 'Tags', type: 'text' },
      { key: 'anwendungen', label: 'Anwendungen', type: 'multiselect', refCategory: 'anwendungen' },
      { key: 'clients', label: 'Clients', type: 'multiselect', refCategory: 'clients' },
      { key: 'server', label: 'Server', type: 'multiselect', refCategory: 'server' },
      { key: 'netzverbindungen', label: 'Netzverbindungen', type: 'multiselect', refCategory: 'netzverbindungen' },
      { key: 'netzkomponenten', label: 'Netzkomponenten', type: 'multiselect', refCategory: 'netzkomponenten' },
      { key: 'raeume', label: 'Räume', type: 'multiselect', refCategory: 'raeume' },
      { key: 'gebaeude', label: 'Gebäude', type: 'multiselect', refCategory: 'gebaeude' },
    ],
  },
  {
    key: 'clients',
    label: 'Clients',
    prefix: 'C',
    icon: '🖱️',
    fields: [
      { key: 'kuerzel', label: 'Kürzel', type: 'text' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'erlaeuterung', label: 'Erläuterung', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS },
      { key: 'anzahl', label: 'Anzahl', type: 'text' },
      { key: 'plattform', label: 'Plattform', type: 'text' },
      { key: 'verantwortlicher', label: 'Verantwortlich / Administrator', type: 'text' },
      { key: 'benutzer', label: 'Benutzer', type: 'text' },
      { key: 'tags', label: 'Tags', type: 'text' },
      { key: 'itSysteme', label: 'IT-Systeme', type: 'multiselect', refCategory: 'all_it' },
      { key: 'netzverbindungen', label: 'Netzverbindungen', type: 'multiselect', refCategory: 'netzverbindungen' },
      { key: 'raeume', label: 'Räume', type: 'multiselect', refCategory: 'raeume' },
      { key: 'gebaeude', label: 'Gebäude', type: 'multiselect', refCategory: 'gebaeude' },
    ],
  },
  {
    key: 'icsSysteme',
    label: 'ICS-Systeme',
    prefix: 'ICS',
    icon: '🏭',
    fields: [
      { key: 'kuerzel', label: 'Kürzel', type: 'text' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'erlaeuterung', label: 'Erläuterung', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS },
      { key: 'anzahl', label: 'Anzahl', type: 'text' },
      { key: 'plattform', label: 'Plattform', type: 'text' },
      { key: 'verantwortlicher', label: 'Verantwortlich / Administrator', type: 'text' },
      { key: 'benutzer', label: 'Benutzer', type: 'text' },
      { key: 'tags', label: 'Tags', type: 'text' },
      { key: 'itSysteme', label: 'IT-Systeme', type: 'multiselect', refCategory: 'all_it' },
      { key: 'netzverbindungen', label: 'Netzverbindungen', type: 'multiselect', refCategory: 'netzverbindungen' },
      { key: 'raeume', label: 'Räume', type: 'multiselect', refCategory: 'raeume' },
      { key: 'gebaeude', label: 'Gebäude', type: 'multiselect', refCategory: 'gebaeude' },
    ],
  },
  {
    key: 'iotSysteme',
    label: 'IoT-Systeme',
    prefix: 'IoT',
    icon: '📡',
    fields: [
      { key: 'kuerzel', label: 'Kürzel', type: 'text' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'erlaeuterung', label: 'Erläuterung', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS },
      { key: 'anzahl', label: 'Anzahl', type: 'text' },
      { key: 'plattform', label: 'Plattform', type: 'text' },
      { key: 'verantwortlicher', label: 'Verantwortlich / Administrator', type: 'text' },
      { key: 'benutzer', label: 'Benutzer', type: 'text' },
      { key: 'tags', label: 'Tags', type: 'text' },
      { key: 'itSysteme', label: 'IT-Systeme', type: 'multiselect', refCategory: 'all_it' },
      { key: 'netzverbindungen', label: 'Netzverbindungen', type: 'multiselect', refCategory: 'netzverbindungen' },
      { key: 'raeume', label: 'Räume', type: 'multiselect', refCategory: 'raeume' },
      { key: 'gebaeude', label: 'Gebäude', type: 'multiselect', refCategory: 'gebaeude' },
    ],
  },
  {
    key: 'raeume',
    label: 'Räume',
    prefix: 'R',
    icon: '🏠',
    fields: [
      { key: 'kuerzel', label: 'Kürzel', type: 'text' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'erlaeuterung', label: 'Erläuterung', type: 'textarea' },
      { key: 'anzahl', label: 'Anzahl', type: 'text' },
      { key: 'verantwortlicher', label: 'Verantwortlich', type: 'text' },
      { key: 'benutzer', label: 'Benutzer', type: 'text' },
      { key: 'tags', label: 'Tags', type: 'text' },
      { key: 'gebaeude', label: 'Gebäude', type: 'multiselect', refCategory: 'gebaeude' },
    ],
  },
  {
    key: 'gebaeude',
    label: 'Gebäude',
    prefix: 'G',
    icon: '🏢',
    fields: [
      { key: 'kuerzel', label: 'Kürzel', type: 'text' },
      { key: 'name', label: 'Name', type: 'text' },
      { key: 'erlaeuterung', label: 'Erläuterung', type: 'textarea' },
      { key: 'anzahl', label: 'Anzahl', type: 'text' },
      { key: 'verantwortlicher', label: 'Verantwortlich', type: 'text' },
      { key: 'benutzer', label: 'Benutzer', type: 'text' },
      { key: 'tags', label: 'Tags', type: 'text' },
    ],
  },
];
